### ISSUE TITLE
udocker openmpi failure

### ISSUE THREAD

**Issue by gdolle** [MSO4SC/feelpp#1] opened 2017-02-27 10:31 UTC
Hi,

I have an error concerning infiniband driver (openfabric) when I use openmpi in the feel++ container.
I guess we have to add it into the container do you have any idea ?

```
nfig-file=cfd1.cfg 
libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
--------------------------------------------------------------------------
[[35229,1],3]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: c6601

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
```

**Comment by gdolle** [comment] 2017-02-27 10:43
NB: If I just mount `/etsc/libibverbs.d` in the container I get
```
libibverbs: Warning: couldn't load driver 'mlx5': libmlx5-rdmav2.so: cannot open shared object file: No such file or directory
libibverbs: Warning: couldn't load driver 'mlx4': libmlx4-rdmav2.so: cannot open shared object file: No such file or directory
libibverbs: Warning: couldn't load driver 'mthca': libmthca-rdmav2.so: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
[[62195,1],3]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: c6601

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
libibverbs: Warning: couldn't load driver 'mlx5': libmlx5-rdmav2.so: cannot open shared object file: No such file or directory
libibverbs: Warning: couldn't load driver 'mlx4': libmlx4-rdmav2.so: cannot open shared object file: No such file or directory
libibverbs: Warning: couldn't load driver 'mthca': libmthca-rdmav2.so: cannot open shared object file: No such file or directory
```

**Comment by victorsndvg** [comment] 2017-02-27 10:45
Hi @gdolle ,

can you provide me a reproducer of the error? (how you launch the container, the input data, etc)

If you can help me to launch the test which is failing reproducing exactly the environment, I can dive deep to solve the problem.

Thanks!

**Comment by gdolle** [comment] 2017-02-27 13:29
Yes,

Using a node
```
udocker pull feelpp/feelpp-toolboxes
compute
export FEELPP_WORKDIR=$TMPDIR
udocker run -v $FEELPP_WORKDIR:/feel feelpp/feelpp-toolboxes

# If you mount also the openib
udocker run -v $FEELPP_WORKDIR:/feel -v -v /etc/libibverbs.d:/etc/libibverbs.d feelpp/feelpp-toolboxes
```
 
In the container, to run an appli in parallel:
```
cd Testcases/CFD/TurekHron
mpirun -np 4 /usr/local/bin/feelpp_toolbox_fluid_2d --config-file=cfd1.cfg
```
Here you'll have the same error.

I think we have to add the openfabric driver in the container, or mount all requires openib libs to make it works. Or maybe there's something I missed ?

**Comment by victorsndvg** [comment] 2017-02-27 14:01
Thanks, I'm going to try and then give you some feedback

**Comment by victorsndvg** [comment] 2017-02-27 16:48
@gdolle,

Currently udocker has not MPI support. We are talking with the developers and they are testing udocker and MPI in FT2 cluster, but is not yet ready.

In the project there are other people studying other possibilities as singularity and shifter, but at the moment we cannot use MPI with docker.

Anyway, I think that the expected interaction of  MPI and the containers will result in a call like the following one:

`mpirun -np 4 udocker run /feel feelpp/feelpp-toolboxes feelpp_toolbox_fluid_2d --config-file=cfd1.cfg`

**Note:** Remember that if you use `udocker run IMAGE-NAME` instead `udocker run CONTAINER-ID` ,you are extracting the image and generating a lot of files every time

**Comment by prudhomm** [comment] 2017-04-06 07:54
@MSO4SC/feelpp I think we should close this issue since udocker is not relevant anymore !
what do you think ?

**Comment by victorsndvg** [comment] 2017-04-06 10:07
For me it's Ok. Maybe we can add a tip to clarify that udocker cannot be used yet with mpi, because it is a recurring question

**Closed as completed** 2017-07-06 20:29 UTC
